name = "jelly-d1-api"
main = "src/index.js"
compatibility_date = "2026-01-10"

# ES Module 모드
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "jellypolice"
database_id = "8f8d4da0-ff7c-4ec2-bd62-33daa6c0b674"

[vars]
API_TOKEN = "JELLY-POLICE-ADMIN-API-2025-!#-#!"
