name = "jelly-d1-api"
main = "src/index.js"
compatibility_date = "2025-12-30"
#  D1 바인딩 이름은 코드에서 env.DB 로 접근
[[d1_databases]]
binding = "DB"
database_name = "jellypolice"
database_id = "8f8d4da0-ff7c-4ec2-bd62-33daa6c0b674"

# 환경변수(선택)
[vars]
API_TOKEN = "JELLY-POLICE-ADMIN-API-2025-!#-#!"
